# Generated by Django 2.1.2 on 2019-01-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muckrockbot', '0005_auto_20190119_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tweet_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
