# Generated by Django 2.1.2 on 2019-01-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muckrockbot', '0006_request_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
